
package com.systemlogic;

import java.util.concurrent.Future;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.Response;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Async", targetNamespace = "http://systemlogic.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Async {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns javax.xml.ws.Response<com.systemlogic.AsyncAddResponse>
     */
    @WebMethod(operationName = "asyncAdd")
    @RequestWrapper(localName = "asyncAdd", targetNamespace = "http://systemlogic.com/", className = "com.systemlogic.AsyncAdd")
    @ResponseWrapper(localName = "asyncAddResponse", targetNamespace = "http://systemlogic.com/", className = "com.systemlogic.AsyncAddResponse")
    public Response<AsyncAddResponse> asyncAddAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "asyncAdd")
    @RequestWrapper(localName = "asyncAdd", targetNamespace = "http://systemlogic.com/", className = "com.systemlogic.AsyncAdd")
    @ResponseWrapper(localName = "asyncAddResponse", targetNamespace = "http://systemlogic.com/", className = "com.systemlogic.AsyncAddResponse")
    public Future<?> asyncAddAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<AsyncAddResponse> asyncHandler);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "asyncAdd", targetNamespace = "http://systemlogic.com/", className = "com.systemlogic.AsyncAdd")
    @ResponseWrapper(localName = "asyncAddResponse", targetNamespace = "http://systemlogic.com/", className = "com.systemlogic.AsyncAddResponse")
    @Action(input = "http://systemlogic.com/Async/asyncAddRequest", output = "http://systemlogic.com/Async/asyncAddResponse")
    public int asyncAdd(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
