
package com.systemlogic;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "AsyncService", targetNamespace = "http://systemlogic.com/", wsdlLocation = "http://localhost:8090/Async/async?wsdl")
public class AsyncService
    extends Service
{

    private final static URL ASYNCSERVICE_WSDL_LOCATION;
    private final static WebServiceException ASYNCSERVICE_EXCEPTION;
    private final static QName ASYNCSERVICE_QNAME = new QName("http://systemlogic.com/", "AsyncService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8090/Async/async?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        ASYNCSERVICE_WSDL_LOCATION = url;
        ASYNCSERVICE_EXCEPTION = e;
    }

    public AsyncService() {
        super(__getWsdlLocation(), ASYNCSERVICE_QNAME);
    }

    public AsyncService(WebServiceFeature... features) {
        super(__getWsdlLocation(), ASYNCSERVICE_QNAME, features);
    }

    public AsyncService(URL wsdlLocation) {
        super(wsdlLocation, ASYNCSERVICE_QNAME);
    }

    public AsyncService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, ASYNCSERVICE_QNAME, features);
    }

    public AsyncService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AsyncService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns Async
     */
    @WebEndpoint(name = "AsyncPort")
    public Async getAsyncPort() {
        return super.getPort(new QName("http://systemlogic.com/", "AsyncPort"), Async.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Async
     */
    @WebEndpoint(name = "AsyncPort")
    public Async getAsyncPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://systemlogic.com/", "AsyncPort"), Async.class, features);
    }

    private static URL __getWsdlLocation() {
        if (ASYNCSERVICE_EXCEPTION!= null) {
            throw ASYNCSERVICE_EXCEPTION;
        }
        return ASYNCSERVICE_WSDL_LOCATION;
    }

}
